### ISSUE TITLE
Master TODO List

### ISSUE THREAD

**Issue by RyanNerd** [RyanNerd/pantry-intake-web#1]
- [x] Create MySQL schema with initial table layouts and export to be shared - Ryan
- [x] Create a PHP/Slim skeleton, commit and push to pantry-intake-app - Ryan 
- [x] Create a React app skeleton, commit and push to pantry-intake-web - Pablo
- [x] Code Slim web-service API endpoints (GET and POST only -- POST is an upsert) - Ryan
    - [x] Households
    - [x] Members
    - [x] Intakes
- [x] Code Pantry Intake Screen layout - Pablo / Ryan
    - [x] Hook in the REST API
    - [x] Testing
- [x] Code Household Search/Maintenance Screen layout - Ryan / Pablo
    - [x] Hook in the REST API
    - [x] Testing
- [x] Code Member Screen layout - Ryan / Pablo
    - [x] Hook in the REST API
    - [x] Testing
- [ ] Code Badge Print Screen - Pablo / Ryan
    - [ ] Hook in the REST API
    - [ ] Testing

-----

- [ ] End to end testing
- [ ] Tweaking aesthetics, cosmetic issues and minor issues

**Comment by RyanNerd** [comment]
Killing this as most of it is done.
